### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by keknuma** [ChristopherMayes/pySuperfish#3]
I tried install it on MacOS. 
When I run docker run I got the following message.

WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
root@8ad7b1565a1d:/data#

**Comment by ChristopherMayes** [comment]
This is a known problem at the moment, the issue is at the docker level with https://github.com/hhslepicka/docker-poisson-superfish-nobin
